# Builds the table of the non-ASCII characters of the script strings, for the string hash.
import hashlib
import re


RX_STR = re.compile(r'"((?:[^"\\]|\\.)*)"', re.S)
DEFAULT_GENERATOR = 'common/kk/tabela_chars.py'


def caracteres(texts):
    seen = set()
    for t in texts:
        for m in RX_STR.finditer(t):
            for ch in m.group(1):
                o = ord(ch)
                if o > 127 and not (0xDC80 <= o <= 0xDCFF):
                    seen.add(ch)
    return sorted(seen)


def table_text(chs, generator=DEFAULT_GENERATOR):
    line_list = [
        '// GENERATED by %s -- do not edit by hand.' % generator,
        '// The %d NON-ASCII characters of the script literals: `DB_SH` (parte_16_hash.j) recognizes' % len(chs),
        '// the whole multibyte character through here (the loose UTF-8 byte has no reliable hash in the engine).',
    ]
    block_list = []
    current = []
    for ch in chs:
        b = ch.encode('utf-8')
        bb = list(b) + [0] * (4 - len(b))
        lit = ch.replace('\\', '\\\\').replace('"', '\\"')
        current.append('    call DB_sh_car("%s",%d,%d,%d,%d,%d)' % (lit, len(b), bb[0], bb[1], bb[2], bb[3]))
        if len(current) >= 1500:
            block_list.append(current)
            current = []
    if current:
        block_list.append(current)
    for i, bl in enumerate(block_list):
        line_list.append('function DB_sh_chars_%d takes nothing returns nothing' % i)
        line_list.extend(bl)
        line_list.append('endfunction')
    line_list.append('function DB_sh_chars takes nothing returns nothing')
    for i in range(len(block_list)):
        line_list.append('    call DB_sh_chars_%d()' % i)
    line_list.append('endfunction')
    return '\n'.join(line_list) + '\n'


def make_table(texts, dest, generator=DEFAULT_GENERATOR):
    chs = caracteres(texts)
    content = table_text(chs, generator)
    open(dest, 'wb').write(content.encode('utf-8'))
    return len(chs), hashlib.sha256(content.encode('utf-8')).hexdigest()[:16]
