# Builds the JASS table of the channel the saved profile is read through.
import os
import re

from doctor.data import objects


RX_ID = re.compile(r'^A\w\w\w$')
MAX_ABILITIES = 400
SLK_SOURCE = ('// `A???`, sorted by id, up to 400 -> 800 slots. Source: port/out/extract_en/Units',
              '// (AbilityData.slk + the *AbilityStrings.txt). Generated by gera_tabela_slots.py.')
W3U_SOURCE = ('// `A???`, sorted by id, up to 400 -> 800 slots. Source: the abilities of the game (CASC) + the',
              '// `war3map.w3a` of the map (`common/kk/objetos.py`, w3u mode). Generated by common/kk/tabela_canal.py.')


def fourcc(s):
    v = 0
    for c in s:
        v = (v << 8) | (ord(c) & 0xFF)
    return v & 0xFFFFFFFF


def ability_slk(units_folder, fields=('tip', 'ubertip')):
    slk = objects.common_module('slk')
    _h, rows = slk.parse_slk(os.path.join(units_folder, 'AbilityData.slk'))
    abils = {}
    for rid, row in rows.items():
        abils[rid] = {k.lower(): v for k, v in row.items() if v not in ('', None)}
    merged = 0
    for fn in sorted(os.listdir(units_folder)):
        if not (fn.lower().endswith('abilitystrings.txt') or fn.lower().endswith('abilityfunc.txt')):
            continue
        for rid, row in slk.parse_ini(os.path.join(units_folder, fn)).items():
            rec = abils.setdefault(rid, {})
            for k, v in row.items():
                lk = k.lower()
                if lk in fields and v not in ('', None):
                    rec[lk] = v
                    merged += 1
    print('fields %s merged from the .txt: %d' % ('/'.join(fields), merged))
    return abils


def w3u_abilities(folder, fields=('tip', 'ubertip')):
    _u, abils, _i = objects.w3u_tables(folder, allowed={'unit': set(), 'ability': set(fields),
                                                        'item': set()})
    return abils


JN_FIELDS = ('tip', 'ubertip', 'untip', 'unubertip', 'researchtip', 'researchubertip')


def jn_ability(folder, method='auto'):
    units = os.path.join(folder, 'Units')
    if method == 'auto':
        method = 'slk' if os.path.isfile(os.path.join(units, 'AbilityData.slk')) else 'w3u'
    abils = ability_slk(units, JN_FIELDS) if method == 'slk' else w3u_abilities(folder, JN_FIELDS)
    best = None
    for rid in sorted(abils):
        rec = abils[rid]
        if not RX_ID.match(rid):
            continue
        comment = [c for c in JN_FIELDS if (rec.get(c) or '').strip().strip('"').strip()]
        if 'tip' not in comment or 'ubertip' not in comment:
            continue
        if best is None or len(comment) > len(best[1]):
            best = (rid, comment)
    return best


def channel_ids(abils):
    ids = sorted(rid for rid, rec in abils.items()
                 if RX_ID.match(rid) and (rec.get('tip') or '').strip() and (rec.get('ubertip') or '').strip())
    print('abilities with Tip AND Ubertip: %d (using the first %d)' % (len(ids), min(len(ids), MAX_ABILITIES)))
    return ids[:MAX_ABILITIES]


def table_text(ids, source=SLK_SOURCE):
    nslots = len(ids) * 2
    L = []
    A = L.append
    A('// ==============================================================================================')
    A('// PROFILE READ CHANNEL TABLE')
    A('//')
    A('// Everything here comes from the BUILD because in JASS there is, at run time, neither the data table')
    A('// of the SLK nor string to FourCC conversion. The list must be THE SAME on both sides (write and')
    A('// read), otherwise the data lands on the wrong ability.')
    A('//')
    A('// Criterion (identical to `build_slots` of rt_natives.lua): ability with `Tip` AND `Ubertip`, id')
    A(source[0])
    A(source[1])
    A('//')
    A('// The DECLARATIONS go to `globals` (JASS only accepts assignment with a literal inside')
    A('// `globals`; a `set` does not go in) and the ASSIGNMENTS stay in the init function.')
    A('// ==============================================================================================')
    A('//@SLOTGLOBALS')
    A('constant integer DB_SLOT_N=%d' % nslots)
    A('constant integer DB_SLOT_ABIL=%d' % len(ids))
    A("string array DB_slot_txt        // 'A000' -- what Preload writes")
    A('integer array DB_slot_code      // the same id as an integer -- BlzGetAbilityTooltip wants an integer')
    A('integer array DB_slot_kind      // 0 = Tip, 1 = ExtendedTooltip')
    A('string array DB_slot_tip_orig   // ORIGINAL tip text, CAPTURED in game (DB_sv_captura)')
    A('string array DB_slot_ubt_orig')
    A('//@ENDSLOTGLOBALS')
    A('')
    A('function DB_slots_init takes nothing returns nothing')
    for i, rid in enumerate(ids):
        code = fourcc(rid)
        A("    set DB_slot_txt[%d]=\"'%s'\"" % (2 * i, rid))
        A('    set DB_slot_code[%d]=%d' % (2 * i, code))
        A('    set DB_slot_kind[%d]=0' % (2 * i))
        A("    set DB_slot_txt[%d]=\"'%s'\"" % (2 * i + 1, rid))
        A('    set DB_slot_code[%d]=%d' % (2 * i + 1, code))
        A('    set DB_slot_kind[%d]=1' % (2 * i + 1))
    A('endfunction')
    A('')
    return '\n'.join(L)


def verify(txt, ids):
    nslots = len(ids) * 2
    pairs = re.findall(r"set DB_slot_txt\[(\d+)\]=\"'(\w{4})'\"\n\s*set DB_slot_code\[\1\]=(\d+)\n"
                       r"\s*set DB_slot_kind\[\1\]=(\d)", txt)
    if len(pairs) != nslots:
        return ['generated %d slots, expected %d' % (len(pairs), nslots)]
    for i, (a, t, c, k) in enumerate(pairs):
        if int(a) != i:
            return ['index %s out of order at %d' % (a, i)]
        if t != ids[i // 2]:
            return ['slot %d = %s, expected %s' % (i, t, ids[i // 2])]
        if int(c) != fourcc(ids[i // 2]):
            return ['code of slot %d = %s' % (i, c)]
        if int(k) != i % 2:
            return ['kind of slot %d = %s' % (i, k)]
    return []


def gera(folder, output, method='auto', source=None):
    units = os.path.join(folder, 'Units')
    if method == 'auto':
        method = 'slk' if os.path.isfile(os.path.join(units, 'AbilityData.slk')) else 'w3u'
    print('mode: %s (%s)' % (method, folder))
    abils = ability_slk(units) if method == 'slk' else w3u_abilities(folder)
    ids = channel_ids(abils)
    print('slots: %d' % (len(ids) * 2))
    if not ids:
        print('FAIL: zero slots -- the source changed; check before generating')
        return 1
    txt = table_text(ids, source or (SLK_SOURCE if method == 'slk' else W3U_SOURCE))
    failures = verify(txt, ids)
    if failures:
        print('FAIL: ' + '; '.join(failures))
        return 1
    open(output, 'wb').write(txt.encode('latin-1', 'replace'))
    print('written: %s (%d B, %d lines)' % (output, os.path.getsize(output), txt.count('\n') + 1))
    print('check: the %d slots match the source, in order, with code and kind' % (len(ids) * 2))
    return 0

