# Builds the table of object fields the map reads at run time.
import os
import re

from doctor.port import class1
from doctor.port import slk_tables


TABLE_NAMES = ('unit', 'ability', 'item')
CODE_LETTER = {'unit': 'U', 'ability': 'A', 'item': 'I'}
JASS_TAB = {'unit': 'DB_TAB_UNIT', 'ability': 'DB_TAB_ABILITY', 'item': 'DB_TAB_ITEM'}
LIMITE = 900


def fourcc(s):
    s = s.strip().strip('"')
    if len(s) != 4:
        return None
    v = 0
    for c in s:
        v = (v << 8) | (ord(c) & 0xFF)
    return v & 0xFFFFFFFF


def jass_hex(v):
    return '0x%08X' % (v & 0xFFFFFFFF)


def jass_name(tab, field_id):
    return 'SLK_%s_%s' % (CODE_LETTER[tab], field_id.upper())


def field_const(tab, field_id):
    return 'DB_C_%s_%s' % (tab.upper(), field_id.upper())


def normalize_fields(fields):
    out = dict((t, set()) for t in TABLE_NAMES)
    if isinstance(fields, dict):
        item_entries = [(t, c) for t, cs in fields.items() for c in cs]
    else:
        item_entries = [tuple(x.strip().split('.', 1)) for x in fields if x.strip()]
    for t, c in item_entries:
        if t not in out:
            raise ValueError('unknown table: %r (unit, ability, item)' % t)
        out[t].add(c.lower())
    return dict((t, sorted(out[t])) for t in TABLE_NAMES)


def script_fields(body_text):
    pairs, failures = class1.script_pairs(body_text)
    fields = normalize_fields(['%s.%s' % k for k in pairs])
    return fields, pairs, failures


def escape_char(ch, controle=False):
    b = ch.encode('utf-8', 'surrogateescape')
    if b == b'"':
        return '\\"'
    if b == b'\\':
        return '\\\\'
    if b in (b'\n', b'\r', b'\t'):
        if controle:
            return {b'\n': '\\n', b'\r': '\\r', b'\t': '\\t'}[b]
        return None
    if b[0] < 32 or b[0] == 127:
        return None
    return b.decode('latin-1')


def literais(field_value, out_limit=LIMITE, controle=False):
    chunks, current, sz = [], [], 0
    for ch in field_value:
        e = escape_char(ch, controle)
        if e is None:
            raise ValueError('control character in the value: %r' % ch)
        if sz + len(e) > out_limit and current:
            chunks.append(''.join(current))
            current, sz = [], 0
        current.append(e)
        sz += len(e)
    chunks.append(''.join(current))
    return ['"%s"' % p for p in chunks]


def build_pairs(data_bytes, tab, field_id):
    pairs, without_id, dup = [], [], []
    seen = {}
    for rid in sorted(data_bytes[tab]):
        v = data_bytes[tab][rid].get(field_id)
        if v is None or v == '':
            continue
        a = fourcc(rid)
        if a is None:
            without_id.append(rid)
            continue
        if a in seen:
            dup.append((rid, seen[a]))
            continue
        seen[a] = rid
        pairs.append((a, v, rid))
    pairs.sort(key=lambda x: x[0])
    return pairs, without_id, dup


DEFAULT_TEXTS = {
    'origin': [
        "// The map reads `(require'jass.slk').<table>[<id>].<field>` -- an object field that the platform",
        "// KK answered through Lua and Reforged has none. The source is that of `slk_tabelas.monta_tabelas_auto`",
        "// (%(source)s).",
        "// Generated by `common/kk/tabela_campos.py` -- DO NOT edit here.",
    ],
    'interface': [
        "// The INTERFACE the rest of the script uses is `DB_slk_get(tabela, id, campo)` (%(where)s).",
        "// The `SLK_<X>_<CAMPO>(id)` functions below are the direct path.",
    ],
    'n_init': None,
}


def _wrap_line(ln, map_width=100):
    if len(ln) <= map_width or not ln.startswith('// '):
        return [ln]
    import textwrap
    return ['// ' + x for x in textwrap.wrap(ln[3:], map_width - 3, break_long_words=False,
                                             break_on_hyphens=False)]


def gera(data_bytes, fields, sitios=None, texts=None, despachante=False, controle=False, source='', where=''):
    fields = normalize_fields(fields)
    sitios = sitios or {}
    tx = dict(DEFAULT_TEXTS)
    tx.update(texts or {})
    L = []
    A = L.append
    n_tab = dict((t, len(data_bytes[t])) for t in TABLE_NAMES)
    n_fields = sum(len(fields[t]) for t in fields)
    info = {}
    for t in TABLE_NAMES:
        for c in fields[t]:
            pairs, without_id, dup = build_pairs(data_bytes, t, c)
            info[(t, c)] = {'pairs': pairs, 'without_id': without_id, 'dup': dup}
    A('// ==============================================================================================')
    A('// TABLE OF THE %d SLK FIELDS THE MAP READS VIA `EXExecuteScript`' % n_fields)
    A('//')
    for line in tx['origin']:
        for x in (_wrap_line(line % {'source': source}) if '%(' in line else [line]):
            A(x)
    A('//')
    for line in tx['interface']:
        for x in (_wrap_line(line % {'where': where}) if '%(' in line else [line]):
            A(x)
    A('//')
    A('// DENOMINATOR (table records): unit %d, ability %d, item %d.' %
      (n_tab['unit'], n_tab['ability'], n_tab['item']))
    A('//')
    A("// SORTED by id in each field: JASS does not guarantee array order, and the search is BINARY --")
    A("// without order it silently returns the wrong result. `_N` is the table size, `_ok` is")
    A("// the auto-initialization flag.")
    A('//')
    A('// %-8s %-12s %-10s %6s %6s %8s' % ('table', 'field_id', 'field_id_col', 'sitios', 'line_list', 'denom.'))
    for t in TABLE_NAMES:
        for c in fields[t]:
            sit = sum(v for k, v in sitios.items() if k[0] == t and k[1].lower() == c)
            A('// %-8s %-12s %-10s %6d %6d %8d'
              % (t, c, field_const(t, c), sit, len(info[(t, c)]['pairs']), n_tab[t]))
    A('// ==============================================================================================')
    A('')
    A('//@SLOTGLOBALS')
    for t in TABLE_NAMES:
        for c in fields[t]:
            n = jass_name(t, c)
            A('constant integer %s_N=%d' % (n, len(info[(t, c)]['pairs'])))
            A('integer array %s_k' % n)
            A('string array %s_v' % n)
            A('boolean %s_ok=false    // the search self-initializes on the 1st read' % n)
    A('// THE STABLE INTERFACE uses these codes: `DB_slk_get(tabela, id, campo)`.')
    A('// The table: DB_TAB_UNIT=0 / DB_TAB_ABILITY=1 / DB_TAB_ITEM=2. The field: the `DB_C_*` below.')
    A('constant integer DB_TAB_UNIT=0')
    A('constant integer DB_TAB_ABILITY=1')
    A('constant integer DB_TAB_ITEM=2')
    code_part = 0
    for t in TABLE_NAMES:
        for c in fields[t]:
            A('constant integer %s=%d' % (field_const(t, c), code_part))
            info[(t, c)]['code'] = code_part
            code_part += 1
    A('//@ENDSLOTGLOBALS')
    A('')

    for t in TABLE_NAMES:
        for c in fields[t]:
            A('')
            d = info[(t, c)]
            fname = jass_name(t, c)
            pairs = d['pairs']
            A('// ==============================================================================================')
            A('// %s.%s -- %d records with a value, out of %d in the SLK | field `%s` of `DB_slk_get`'
              % (t, c, len(pairs), n_tab[t], field_const(t, c)))
            if d['without_id']:
                A('// DISCARDED (id without 4 characters): %d -> %s' % (len(d['without_id']), d['without_id'][:8]))
            if d['dup']:
                A('// DISCARDED (repeated id): %d -> %s' % (len(d['dup']), d['dup'][:4]))
            A('// ==============================================================================================')
            init_lines = []
            for i, (a, v, _rid) in enumerate(pairs):
                lit = literais(v, controle=controle)
                init_lines.append('    set %s_k[%d]=%s' % (fname, i, jass_hex(a)))
                init_lines.append('    set %s_v[%d]=%s' % (fname, i, lit[0]))
                for k in range(1, len(lit)):
                    init_lines.append('    set %s_v[%d]=%s_v[%d]+%s' % (fname, i, fname, i, lit[k]))
            A('function %s_init takes nothing returns nothing' % fname)
            L.extend(init_lines)
            A('endfunction')
            A('')
            A('// Binary search. Returns the column value, or "" when the id is absent from the table')
            A('// (the Lua runtime returned nil and `__tostr` turned it into "" -- this is the same semantics).')
            A('function %s takes integer id returns string' % fname)
            A('    local integer lo=0')
            A('    local integer hi=%s_N-1' % fname)
            A('    local integer meio')
            A('    if not %s_ok then' % fname)
            A('        set %s_ok=true' % fname)
            A('        call %s_init()' % fname)
            A('    endif')
            A('    if id==0 then')
            A('        return ""')
            A('    endif')
            A('    loop')
            A('        exitwhen lo>hi')
            A('        set meio=(lo+hi)/2')
            A('        if %s_k[meio]==id then' % fname)
            A('            return %s_v[meio]' % fname)
            A('        elseif %s_k[meio]<id then' % fname)
            A('            set lo=meio+1')
            A('        else')
            A('            set hi=meio-1')
            A('        endif')
            A('    endloop')
            A('    return ""')
            A('endfunction')
            d['custo'] = sum(len(x.encode('latin-1')) + 1 for x in init_lines)
            d['sliced'] = sum(1 for _a, v, _r in pairs if len(literais(v, controle=controle)) > 1)
            d['max_literals'] = max((len(max(literais(v, controle=controle), key=len)) for _a, v, _r in pairs),
                                    default=0)
    n_init = tx.get('n_init')
    A('')
    A('// ==============================================================================================')
    A('// DB_slk_init -- initializes the %d fields at once. NOT mandatory'
      % (n_fields if n_init is None else n_init) + ' (each search is')
    A('// self-initializes), but calling it in the map init avoids paying the cost in the middle of the game.')
    A('// ==============================================================================================')
    A('function DB_slk_init takes nothing returns nothing')
    for t in TABLE_NAMES:
        for c in fields[t]:
            fname = jass_name(t, c)
            A('    set %s_ok=true' % fname)
            A('    call %s_init()' % fname)
    A('endfunction')
    A('')
    if despachante:
        L.extend(gen_dispatcher(fields))
    return L, info


def dispatcher_function(fields):
    fields = normalize_fields(fields)
    L = ['function DB_slk_get takes integer tabela,integer id,integer campo returns string',
         '    if id==0 then',
         '        return ""',
         '    endif']
    first_tab = True
    for t in TABLE_NAMES:
        if not fields[t]:
            continue
        L.append('    %s tabela==%s then' % ('if' if first_tab else 'elseif', JASS_TAB[t]))
        first_tab = False
        for i, c in enumerate(fields[t]):
            L.append('        %s campo==%s then' % ('if' if i == 0 else 'elseif', field_const(t, c)))
            L.append('            return %s(id)' % jass_name(t, c))
        L.append('        endif')
        L.append('        return ""')
    if not first_tab:
        L.append('    endif')
    L.append('    return ""')
    L.append('endfunction')
    return L


def gen_dispatcher(fields):
    fields = normalize_fields(fields)
    n = sum(len(v) for v in fields.values())
    L = ['',
         '// ==============================================================================================',
         '// DB_slk_get -- THE STABLE INTERFACE for reading an object field (CLASS 1), GENERATED together with',
         '// the table (the map has no hand-written dispatcher).',
         '//',
         '//     function DB_slk_get takes integer tabela,integer id,integer campo returns string',
         '//',
         '//   table : DB_TAB_UNIT=0 / DB_TAB_ABILITY=1 / DB_TAB_ITEM=2.',
         "//   id     : the object id as a FourCC INTEGER (`'hfoo'`, `GetItemTypeId(it)`...).",
         '//   field  : one of the %d `DB_C_*` above.' % n,
         '//   return: the value as `jass.slk` returned it (text), or "" when the id is absent from the',
         '//            table or the field has no value.',
         '//',
         '// The sites `EXExecuteScript("(require\'jass.slk\')...")` of the map become calls to this function',
         '// by the 3d rewrite (`common/kk/classe1.py`).',
         '// ==============================================================================================']
    return L + dispatcher_function(fields) + ['']


RX_K = re.compile(r'^    set (\w+)_k\[(\d+)\]=(0x[0-9A-F]{8})$')
RX_V1 = re.compile(r'^    set (\w+)_v\[(\d+)\]=("(?:[^"\\]|\\.)*")$')
RX_V2 = re.compile(r'^    set (\w+)_v\[(\d+)\]=(\w+)_v\[\2\]\+("(?:[^"\\]|\\.)*")$')


def unescape(lit):
    assert lit[0] == '"' and lit[-1] == '"', lit[:20]
    body = lit[1:-1]
    out = []
    i = 0
    while i < len(body):
        if body[i] == '\\':
            c = body[i + 1]
            if c == '"':
                out.append('"')
            elif c == '\\':
                out.append('\\')
            elif c == 'n':
                out.append('\n')
            elif c == 'r':
                out.append('\r')
            elif c == 't':
                out.append('\t')
            else:
                raise AssertionError('unexpected escape: \\%s' % c)
            i += 2
            continue
        out.append(body[i])
        i += 1
    return ''.join(out)


def verify(file_path, info, fields):
    fields = normalize_fields(fields)
    txt = open(file_path, 'rb').read().decode('latin-1')
    line_list = txt.split('\n')
    vals = {}
    ks = {}
    for line in line_list:
        m = RX_K.match(line)
        if m:
            ks.setdefault(m.group(1), {})[int(m.group(2))] = int(m.group(3), 16)
            continue
        m = RX_V1.match(line)
        if m:
            vals.setdefault(m.group(1), {})[int(m.group(2))] = [unescape(m.group(3))]
            continue
        m = RX_V2.match(line)
        if m:
            vals.setdefault(m.group(1), {})[int(m.group(2))].append(unescape(m.group(4)))
    failures = []
    n = 0
    for t in TABLE_NAMES:
        for c in fields[t]:
            fname = jass_name(t, c)
            pairs = info[(t, c)]['pairs']
            if len(ks.get(fname, {})) != len(pairs) or len(vals.get(fname, {})) != len(pairs):
                failures.append('%s: generated %d keys and %d values, expected %d'
                                % (fname, len(ks.get(fname, {})), len(vals.get(fname, {})), len(pairs)))
                continue
            for i, (a, v, rid) in enumerate(pairs):
                n += 1
                if ks[fname][i] != a:
                    failures.append('%s[%d]: key 0x%08X != 0x%08X (%s)' % (fname, i, ks[fname][i], a, rid))
                expected_len = v.encode('utf-8', 'surrogateescape').decode('latin-1')
                obtained = ''.join(vals[fname][i])
                if obtained != expected_len:
                    failures.append('%s[%d] (%s): divergent value\n     expected %r\n     got      %r'
                                    % (fname, i, rid, expected_len[:120], obtained[:120]))
            kl = [ks[fname][i] for i in range(len(pairs))]
            for i, (a, v, rid) in enumerate(pairs):
                lo, hi = 0, len(kl) - 1
                achou = -1
                while lo <= hi:
                    middle = (lo + hi) // 2
                    if kl[middle] == a:
                        achou = middle
                        break
                    elif kl[middle] < a:
                        lo = middle + 1
                    else:
                        hi = middle - 1
                if achou != i:
                    failures.append('%s: binary search for id %s found %d, expected %d' % (fname, rid, achou, i))
                    break
    return failures, n


def check_interface_text(txt, fields, failures, label):
    fields = normalize_fields(fields)
    in_use = set(re.findall(r'\b(DB_C_[A-Z0-9_]+)\b', txt))
    generated = set(field_const(t, c) for t in fields for c in fields[t])
    if in_use != generated:
        failures.append(
            'DRIFT in the interface (%s): in the dispatcher and not in table %s | in the table and not in the '
            'dispatcher %s' % (label, sorted(in_use - generated), sorted(generated - in_use))
        )
    name_list = set(re.findall(r'\b(SLK_[UAI]_[A-Z0-9_]+)\(', txt))
    missing_items = set(jass_name(t, c) for t in fields for c in fields[t]) - name_list
    if missing_items:
        failures.append('the interface (%s) does not call these table functions: %s' % (label, sorted(missing_items)))
    return len(in_use)


def check_interface(file_path, fields, failures):
    if not os.path.isfile(file_path):
        failures.append('the interface is missing: %s' % file_path)
        return 0
    txt = open(file_path, 'rb').read().decode('latin-1')
    return check_interface_text(txt, fields, failures, file_path)


def run_action(ext, output, fields, sitios=None, interface=None, texts=None, data_bytes=None, method='auto',
               w3u=None, controle=False, total_label=None, extras=None, by_name=False):
    fields = normalize_fields(fields)
    print('source: %s' % ext)
    details = {}
    source = 'data passed by the project'
    if callable(data_bytes):
        data_bytes = data_bytes()
    if data_bytes is None:
        mode_used, units, abils, items = slk_tables.build_auto_tables(
            ext, method=method, extras=fields, stats=details, **(w3u or {}))
        data_bytes = {'unit': units, 'ability': abils, 'item': items}
        if mode_used == 'w3u':
            source = ('w3u mode: the game base through CASC %s, layer %s, language %s, with war3map.w3u/w3t/w3a '
                      'and the war3map.wts of the map on top' % (details.get('casc'), details.get('balance') or 'base',
                                                                 details.get('locale')))
            print('w3u mode: layer %s (%s); language %s; CASC %s; wts %s (%d texts)'
                  % (details.get('balance'), details.get('balance_reason'), details.get('locale'), details.get('casc'),
                     details.get('wts'), details.get('wts_texts', 0)))
            for t in TABLE_NAMES:
                ro = details['objects'][t]
                print('   %-8s game base %5d | from the map: %d originals modified, %d new, %d modifications'
                      ' | no base in the game: %d %s' % (t, ro['game_base'], ro['originals'], ro['new_ones'],
                                                         ro['mods'], len(ro['no_base']), ro['no_base'][:4]))
            print('   TRIGSTR resolved by the wts: %d; missing from the wts: %d %s; fields without metadata: %d %s'
                  % (details['count']['trigstr'], len(details['missing_trigstr']),
                     sorted(details['missing_trigstr'])[:6], sum(details['unknown_fields'].values()),
                     dict(details['unknown_fields'].most_common(6))))
        else:
            source = 'SLK mode: the Units/*.slk of the data folder + *Strings/Func/Skin.txt + war3map.w3a/w3u'
    print(
        'records: unit %d  ability %d  item %d'
        % (len(data_bytes['unit']), len(data_bytes['ability']), len(data_bytes['item']))
    )
    empty_files = sum(1 for r in data_bytes['ability'].values() if not r)
    print('ability records with ZERO stored fields (they emit nothing anywhere): %d'
          % empty_files)
    where = ('documented in `%s`' % os.path.basename(interface)) if interface else 'generated at the end of this file'
    line_list, info = gera(data_bytes, fields, sitios=sitios, texts=texts, despachante=interface is None,
                           controle=controle, source=source, where=where)
    if by_name:
        from doctor.port import slk_dynamic
        line_list += slk_dynamic.functions_by_name(fields, field_const)
    if os.path.dirname(output) and not os.path.isdir(os.path.dirname(output)):
        os.makedirs(os.path.dirname(output))
    open(output, 'w', encoding='latin-1', newline='\n').write('\n'.join(line_list) + '\n')
    sz = os.path.getsize(output)
    print('written: %s (%d B = %.1f KB, %d lines)' % (output, sz, sz / 1024.0, len(line_list)))

    total = pair_sum = 0
    print('\n%-8s %-12s %6s %7s %9s %9s %8s %8s' %
          ('table', 'field_id', 'code_part', 'line_list', 'value_B', 'jass_B', 'KB', 'sliced'))
    for t in TABLE_NAMES:
        sub = 0
        for c in fields[t]:
            d = info[(t, c)]
            byte_total = sum(len(v.encode('utf-8', 'surrogateescape')) for _a, v, _r in d['pairs'])
            print('%-8s %-12s %6d %7d %9d %9d %8.1f %8d'
                  % (t, c, d['code'], len(d['pairs']), byte_total, d['custo'], d['custo'] / 1024.0,
                     d['sliced']))
            sub += d['custo']
            pair_sum += len(d['pairs'])
        print('%-8s %-12s %6s %7s %9s %9d %8.1f' % (t, '(subtotal)', '', '', '', sub, sub / 1024.0))
        total += sub
    n_fields = sum(len(v) for v in fields.values())
    print('%-8s %-12s %6s %7d %9s %9d %8.1f  <- TOTAL (%.2f MB)' %
          (total_label or ('%d fields' % n_fields), '', '', pair_sum, '', total, total / 1024.0,
           total / 1048576.0))
    print('   (valor_B = bytes of the raw values; jass_B = bytes of the `set` lines of the table)')

    failures, n = verify(output, info, fields)
    print('\nSELF-CHECK: %d pairs checked against the generated file (key + value + search '
          'binary), %d failure(s)' % (n, len(failures)))
    for f in failures[:20]:
        print('   FAIL: %s' % f)
    if interface:
        in_use = check_interface(interface, fields, failures)
        print('interface: %s (%d field codes referenced)' % (interface, in_use))
    else:
        in_use = check_interface_text('\n'.join(dispatcher_function(fields)), fields, failures,
                                      'generated dispatcher')
        print('interface: DB_slk_get dispatcher GENERATED at the end of %s (%d field codes)'
              % (os.path.basename(output), in_use))
    for f in extras or []:
        f(info, failures)
    info['_pixel_data'] = data_bytes
    info['_rel'] = details
    return failures, info, data_bytes

