# Assembles the port layer: the JASS parts that give the platform natives a body on Warcraft III 3.0.
import json
import os
import re
import subprocess
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
KK_COMPAT = os.path.join(HERE, 'compat')
PJASS_PY = os.path.join(HERE, 'pjass.py')
REF_30 = os.path.normpath(os.path.join(HERE, '..', 'ref', '3.0'))
RX_PARAM = re.compile(r'\{\{(KK_[A-Z0-9_]+)\}\}')
RX_INCLUDE = re.compile(r'(?m)^[ \t]*//\{\{KK_INCLUI:([a-z0-9_]+)\}\}[ \t]*\r?\n')
RX_IF = re.compile(r'(?m)^[ \t]*//\{\{KK_(SE|FIMSE):(KK_[A-Z0-9_]+)\}\}[ \t]*\r?\n')

ROOT = None
PARTES = []
WAVE1_PARTS = []
REF = None
ANALYSIS = None
DEFAULT_OUTPUT = None
PARAMETROS = None
MAP_NATIVES = None
COMPAT = None
OUT = None
GENERATOR = 'common/kk/camada.py'
INJECTOR = 'injeta.py'
BLIZZARD_HEADER = None
LAYER_HEADER = None
GATE = None
NO_STUB = set()


def configure_layer(root, pieces, wave1_parts=(), ref=None, analise=None, output=None, parameters=None,
                    map_natives=None, compat=None, out=None, generator=None, injector=None, blizzard_header=None,
                    layer_header=None, portao=None, no_stub=()):
    global ROOT, PARTES, WAVE1_PARTS, REF, ANALYSIS, DEFAULT_OUTPUT, PARAMETROS, MAP_NATIVES, COMPAT, OUT
    global GENERATOR, INJECTOR, BLIZZARD_HEADER, LAYER_HEADER, GATE, NO_STUB
    ROOT = os.path.abspath(root)
    PARTES = list(pieces)
    WAVE1_PARTS = list(wave1_parts)
    REF = ref or REF_30
    ANALYSIS = analise or os.path.join(ROOT, 'port', 'analysis')
    DEFAULT_OUTPUT = output or os.path.join(ROOT, 'scripts', 'blizzard.j')
    PARAMETROS = parameters or os.path.join(ROOT, 'port', 'kk_parametros.json')
    COMPAT = compat or os.path.join(ROOT, 'port', 'compat')
    OUT = out or os.path.join(ROOT, 'port', 'out')
    MAP_NATIVES = map_natives or os.path.join(COMPAT, 'part_0_map_natives.j')
    GENERATOR = generator or 'common/kk/camada.py'
    INJECTOR = injector or 'injeta.py'
    BLIZZARD_HEADER = list(blizzard_header) if blizzard_header else None
    LAYER_HEADER = list(layer_header) if layer_header else None
    GATE = list(portao) if portao else None
    NO_STUB = set(no_stub or ())


def _demand_check():
    if ROOT is None:
        raise SystemExit('layer: call configura(raiz, partes) first (or --raiz= on the command line)')


MARKS = {
    'natives': ('//@CAMADA_NATIVES', '//@FIM_CAMADA_NATIVES'),
    'globals_block': ('//@CAMADA_GLOBALS', '//@FIM_CAMADA_GLOBALS'),
    'functions': ('//@CAMADA_FUNCTIONS', '//@FIM_CAMADA_FUNCTIONS'),
}

KW_JASS = set("""if and or not return function then else elseif endif loop endloop exitwhen set call
local globals endglobals takes returns nothing array constant native type extends debug in null true
false endfunction""".split())

RX_SIGNATURE = re.compile(
    r'(?m)^\s*function\s+([A-Za-z_]\w*)\s+takes\s+(.*?)\s+returns\s+(\w+)\s*$')
RX_ANY_DEF = re.compile(
    r'(?m)^\s*(?:constant\s+)?(?:native|function)\s+([A-Za-z_]\w*)\s+takes')


def default_header():
    return ['//===========================================================================',
            '// blizzard.j -- DELIVERY of the JASS route of a KK port (KK framework, common/kk)',
            '//',
            '// This file is SELF-CONTAINED on purpose: it is the whole blizzard.j of the reference PLUS the',
            '// layer block at the end. The `globals` below is the one of the game: the variables of the layer go in',
            '// MERGED into it, because pjass treats `globals` as unique per unit.',
            '//',
            '// This file is GENERATED by %s from the parts of the layer.' % GENERATOR,
            '// Do not edit here: edit the parts.',
            '//===========================================================================']


def default_layer_header():
    return ['// ==============================================================================================',
            '// OUR LAYER, ONLY IT -- goes into `%s` INSIDE `war3map.j`.' % INJECTOR,
            '//',
            '// GENERATED by %s --camada=...  DO NOT EDIT.' % GENERATOR,
            '// %(score)s',
            '//',
            '// 1. NATIVES  -> absolute top of `war3map.j`, before `globals` (pjass refuses',
            '//                `native` after any `function`).',
            '// 2. GLOBALS  -> INSIDE the single `globals ... endglobals` of the map (pjass refuses two).',
            '// 3. FUNCTIONS-> after `endglobals` and BEFORE the first function of the map (the calls',
            '//                are in the body of its functions).',
            '// ==============================================================================================']


def part_path(fname):
    if os.path.isabs(fname):
        return fname
    if fname.startswith('KK:'):
        return os.path.join(KK_COMPAT, *fname[3:].split('/'))
    if fname.startswith('KKN:'):
        return os.path.join(KK_COMPAT, *fname[4:].split('/'))
    _demand_check()
    if fname.startswith('out/'):
        return os.path.join(OUT, *fname[4:].split('/'))
    return os.path.join(COMPAT, *fname.split('/'))


def part_names(p):
    return tuple(p) if isinstance(p, (tuple, list)) else (p,)


def display_name(p):
    n = part_names(p)[0]
    return n[4:] if n.startswith('KKN:') else n[3:] if n.startswith('KK:') else n


def kk_files():
    out = []
    for p in PARTES + WAVE1_PARTS:
        for n in part_names(p):
            if n.startswith('KK:') or n.startswith('KKN:'):
                out.append(part_path(n))
    return out


def read_parameters(latin1=True):
    _demand_check()
    if not os.path.isfile(PARAMETROS):
        return {}
    raw_bytes = json.load(open(PARAMETROS, encoding='utf-8'))
    params = {}
    for k, v in raw_bytes.items():
        if k.startswith('_'):
            continue
        if not re.match(r'^KK_[A-Z0-9_]+$', k) or not isinstance(v, str) or '"' in v or '\n' in v or '\r' in v:
            raise SystemExit('ABORT: invalid parameter in %s: %r' % (PARAMETROS, k))
        params[k] = v.encode('utf-8').decode('latin-1') if latin1 else v
    return params


def apply_parameters(body_text, origin, params, in_use=None):
    def swap(m):
        k = m.group(1)
        if k not in params:
            raise SystemExit('ABORT: %s asks for {{%s}} and %s does not have that value' % (origin, k, PARAMETROS))
        if in_use is not None:
            in_use.add(k)
        return params[k]
    return RX_PARAM.sub(swap, body_text)


def include_path(fname):
    _demand_check()
    return os.path.join(COMPAT, 'kk_%s.j' % fname)


def apply_includes(body_text, origin, ler):
    def swap(m):
        cpath = include_path(m.group(1))
        if not os.path.isfile(cpath):
            raise SystemExit(
                'ABORT: %s asks for the map section %s, which does not exist (each map declares each point; '
                'nothing to do, the file exists EMPTY)' % (origin, cpath)
            )
        t = ler(cpath)
        if t and not t.endswith('\n'):
            raise SystemExit('ABORT: the snippet %s does not end in a line break' % cpath)
        if RX_INCLUDE.search(t):
            raise SystemExit('ABORT: section %s has another inclusion (no inclusion inside a section)' % cpath)
        return t
    return RX_INCLUDE.sub(swap, body_text)


def apply_conditionals(body_text, origin, params, in_use=None):
    if '{{KK_SE:' not in body_text and '{{KK_FIMSE:' not in body_text:
        return body_text
    out = []
    pos = 0
    aberto = None
    for m in RX_IF.finditer(body_text):
        kind, fname = m.group(1), m.group(2)
        if kind == 'SE':
            if aberto:
                raise SystemExit('ABORT: %s: //{{KK_SE:%s}} inside the block //{{KK_SE:%s}}' % (origin, fname, aberto))
            aberto = fname
            out.append(body_text[pos:m.start()])
        else:
            if aberto != fname:
                raise SystemExit(
                    'ABORT: %s: //{{KK_FIMSE:%s}} without the //{{KK_SE:%s}} open' % (origin, fname, fname)
                )
            if in_use is not None and fname in params:
                in_use.add(fname)
            if params.get(fname) == 'true':
                out.append(body_text[pos:m.start()])
            aberto = None
        pos = m.end()
    if aberto:
        raise SystemExit('ABORT: %s: //{{KK_SE:%s}} without the //{{KK_FIMSE:%s}}' % (origin, aberto, aberto))
    out.append(body_text[pos:])
    t = ''.join(out)
    if '{{KK_SE:' in t or '{{KK_FIMSE:' in t:
        raise SystemExit('ABORT: %s: conditional block marker outside a line of its own' % origin)
    return t


def layer_files():
    _demand_check()
    from_project = sorted(os.listdir(COMPAT)) if os.path.isdir(COMPAT) else []
    return [os.path.join(COMPAT, f) for f in from_project if f.endswith('.j')] + kk_files()


def _read_utf8(file_path):
    return open(file_path, 'rb').read().decode('utf-8', 'surrogateescape')


def read_part_utf8(file_path, params=None):
    params = read_parameters(latin1=False) if params is None else params
    t = apply_includes(_read_utf8(file_path), file_path, _read_utf8)
    t = apply_conditionals(t, file_path, params)
    return apply_parameters(t, file_path, params)


def arg(fname, default_value=None, argv=None):
    for a in (sys.argv if argv is None else argv):
        if a.startswith('--' + fname + '='):
            return a[len(fname) + 3:]
    return default_value


def war3map_source():
    _demand_check()
    for c in ('port/extract/war3map.j', 'scripts/war3map.j'):
        p = os.path.join(ROOT, *c.split('/'))
        if os.path.isfile(p):
            return p
    return os.path.join(ROOT, 'scripts', 'war3map.j')


def read_latin1(p):
    return open(p, 'rb').read().decode('latin-1').replace('\r\n', '\n')


def types_of(takes):
    if takes.strip() in ('nothing', ''):
        return []
    return [p.strip().split()[0] for p in takes.split(',')]


def jass_signature(fname, takes, ret):
    types = types_of(takes)
    if not types:
        return 'function %s takes nothing returns %s' % (fname, ret)
    return 'function %s takes %s returns %s' % (
        fname, ', '.join('%s a%d' % (t, i + 1) for i, t in enumerate(types)), ret)


def make_stubs(decl, order, implemented, heading=None):
    pend = [n for n in order if n not in implemented]
    L = []
    A = L.append
    A('// ==============================================================================================')
    if heading:
        A('// %s' % heading)
    else:
        A('// PART 3 -- STUBS: %d natives declared in the map that still have NO body.' % len(pend))
    A('//')
    A('// EXACT signature copied from the declaration in `war3map.j`. Empty body: it is what the platform')
    A('// would do with a native it does not know. Injected by `%s`.' % os.path.basename(GENERATOR))
    A('// ==============================================================================================')
    A('')
    if any(decl[n]['ret'] == 'code' for n in pend):
        A('function KK_codigo_vazio takes nothing returns nothing')
        A('endfunction')
        A('')
    for n in pend:
        d = decl[n]
        A(jass_signature(n, d['takes'], d['ret']))
        neutral_value = {'integer': '0', 'real': '0.0', 'boolean': 'false', 'string': '""'}.get(d['ret'])
        if d['ret'] == 'nothing':
            A('endfunction')
        elif neutral_value is not None:
            A('    return %s' % neutral_value)
            A('endfunction')
        elif d['ret'] == 'code':
            A('    return function KK_codigo_vazio')
            A('endfunction')
        else:
            A('    return null')
            A('endfunction')
        A('')
    return '\n'.join(L)


RX_GLOBAL = re.compile(
    r'^\s*(constant\s+)?(integer|real|boolean|string|handle|code|hashtable|timer|trigger|group|'
    r'force|region|rect|unit|item|player|effect|ability|destructable|dialog|button|lightning|widget|location|'
    r'image|texttag|ubersplat|sound|quest|questitem|defeatcondition|timerdialog|leaderboard|'
    r'multiboard|multiboarditem|trackable|framehandle|originframetype|framepointtype|'
    r'frameeventtype|textaligntype|oskeytype|eventid|eventtype|playerevent|playerunitevent|'
    r'unitevent|widgetevent|dialogevent|unitstate|abilityreallevelfield|abilityintegerlevelfield|'
    r'abilitystringlevelfield|abilitybooleanlevelfield|unitrealfield|unitintegerfield|'
    r'unitstringfield|unitbooleanfield|itemrealfield|itemintegerfield|itemstringfield|'
    r'limitop)\s+(array\s+)?[A-Za-z_]\w*\s*(=[^\r\n]*)?$')


RX_FUNC_DEF = re.compile(r'(?m)^function\s+([A-Za-z_]\w*)\s+takes')
RX_CALL = re.compile(r'(?<![\w.])([A-Za-z_]\w*)\s*\(|(?<![\w.])function\s+([A-Za-z_]\w*)')


def sort_by_dependency(body_text, already_defined):
    block_list = []
    pos = 0
    for m in RX_FUNC_DEF.finditer(body_text):
        fname = m.group(1)
        first_pos = body_text.rfind('\n', 0, m.start()) + 1
        end_pos = body_text.find('\nendfunction', m.end())
        if end_pos < 0:
            continue
        end_pos += len('\nendfunction')
        block_list.append((fname, first_pos, end_pos))
    if not block_list:
        return body_text, 0
    head_text = body_text[:block_list[0][1]]
    tail = body_text[block_list[-1][2]:]
    bodies = {}
    order = []
    for fname, i, f in block_list:
        if fname in bodies:
            continue
        bodies[fname] = body_text[i:f]
        order.append(fname)
    deps = {}
    for fname in order:
        d = set()
        body_without_decl = bodies[fname].split('\n', 1)[1] if '\n' in bodies[fname] else ''
        for m in RX_CALL.finditer(body_without_decl):
            tgt = m.group(1) or m.group(2)
            if tgt != fname and tgt in bodies:
                d.add(tgt)
        deps[fname] = d
    output = []
    done = set()
    remaining_names = list(order)
    while remaining_names:
        progress = False
        for fname in list(remaining_names):
            if all((x in done) or (x in already_defined) for x in deps[fname]):
                output.append(fname)
                done.add(fname)
                remaining_names.remove(fname)
                progress = True
        if not progress:
            chosen_name = min(remaining_names, key=lambda n: (len([x for x in deps[n] if x not in done]),
                                                              order.index(n)))
            print('WARNING: dependency cycle -- broken at %s' % chosen_name)
            output.append(chosen_name)
            done.add(chosen_name)
            remaining_names.remove(chosen_name)
    new = head_text + '\n\n'.join(bodies[n] for n in output) + '\n' + tail
    return new, len(order)


def implemented_names(*texts):
    matches = set()
    for t in texts:
        matches |= set(re.findall(r'(?m)^function\s+([A-Za-z_]\w*)\s+takes', t))
    return matches


def declaracoes(body_text):
    d = {}
    for m in RX_SIGNATURE.finditer(body_text):
        d[m.group(1)] = {'takes': m.group(2), 'ret': m.group(3)}
    return d


def called_names(body_text):
    matches = set()
    for m in RX_CALL.finditer(body_text):
        n = m.group(1) or m.group(2)
        if n not in KW_JASS:
            matches.add(n)
    return matches


def smoke_stubs(map_decl, order, in_layer, functions_text, map_txt, engine):
    A = [n for n in order if n not in in_layer]
    real_blocks = declaracoes(functions_text)
    called = called_names(map_txt)
    B = sorted(n for n in called
               if n in real_blocks and n not in set(A) and n not in engine)
    t1 = ('SMOKE (A) -- %d natives DECLARED by the map: EXACT signature, neutral body.'
          % len(A))
    t2 = ('SMOKE (B) -- %d functions of the layer that `war3map.j` CALLS: neutral body.' % len(B))
    return (make_stubs(map_decl, A, set(), t1) + '\n\n' + make_stubs(real_blocks, B, set(), t2),
            sorted(A), B)


def write_layer(file_path, natives, globals_txt, functions_txt, score):
    L = [line % {'score': score} if '%(score)s' in line else line
         for line in (LAYER_HEADER or default_layer_header())]
    for hash_key, body_text in (('natives', natives), ('globals_block', globals_txt), ('functions', functions_txt)):
        begin, end_pos = MARKS[hash_key]
        L.append(begin)
        L.append(body_text)
        L.append(end_pos)
    if not os.path.isdir(os.path.dirname(os.path.abspath(file_path))):
        os.makedirs(os.path.dirname(os.path.abspath(file_path)))
    raw_bytes = ('\n'.join(L) + '\n').encode('latin-1', 'replace')
    open(file_path, 'wb').write(raw_bytes)
    return raw_bytes


def map_native_declarations(origin):
    map_path = open(origin, 'rb').read().decode('utf-8', 'surrogateescape')
    map_path = re.sub(r'\r(?!\n)', '\n', map_path)
    decl = {}
    order = []
    for m in re.finditer(r'(?m)^\s*native\s+([A-Za-z_]\w*)\s+takes\s+(.*?)\s+returns\s+(\w+)', map_path):
        decl[m.group(1)] = {'takes': m.group(2).strip(), 'ret': m.group(3)}
        order.append(m.group(1))
    return decl, order


def _variable_name(ln):
    return ln.split('//')[0].split('=')[0].split()[-1]


def filter_conditional_natives(body_text, origin, decl, engine=()):
    bodies = {}
    rest = []
    pos = 0
    for m in RX_FUNC_DEF.finditer(body_text):
        if m.start() < pos:
            continue
        end_pos = body_text.find('\nendfunction', m.end())
        if end_pos < 0:
            raise SystemExit('ABORT: %s: function %s has no endfunction' % (origin, m.group(1)))
        end_pos += len('\nendfunction')
        rest.append(body_text[pos:m.start()])
        bodies.setdefault(m.group(1), body_text[m.start():end_pos])
        pos = end_pos
    rest.append(body_text[pos:])
    vars_ = [line.strip() for line in ''.join(rest).split('\n') if RX_GLOBAL.match(line.split('//')[0].rstrip())]
    entra = set()
    for n, body in bodies.items():
        if n not in decl or n in engine:
            continue
        a = RX_SIGNATURE.search(body)
        if not a or types_of(a.group(2)) != types_of(decl[n]['takes']) or a.group(3) != decl[n]['ret']:
            print('WARNING: %s: %s has another signature in the map (takes %s returns %s): the stub stays'
                  % (os.path.basename(origin), n, decl[n]['takes'], decl[n]['ret']))
            continue
        entra.add(n)
    work_queue = list(entra)
    while work_queue:
        n = work_queue.pop()
        for m in RX_CALL.finditer(bodies[n].split('\n', 1)[1]):
            tgt = m.group(1) or m.group(2)
            if tgt in bodies and tgt not in entra and tgt not in decl:
                entra.add(tgt)
                work_queue.append(tgt)
    if not entra:
        return ''
    used = '\n'.join(bodies[n] for n in entra)
    output = [line for line in vars_ if re.search(r'\b%s\b' % re.escape(_variable_name(line)), used)]
    output += [bodies[n] for n in bodies if n in entra]
    return '\n'.join(output) + '\n'


def _defined_in_fixed_parts(listing, params):
    name_list = set()
    for p in listing:
        for n in part_names(p):
            file_path = part_path(n)
            if n.startswith('KKN:') or not os.path.isfile(file_path):
                continue
            body_text = apply_includes(read_latin1(file_path), file_path, read_latin1)
            name_list |= implemented_names(apply_conditionals(body_text, file_path, params))
    return name_list


def read_parts(argv=None):
    _demand_check()
    listing = PARTES + (WAVE1_PARTS if '--onda1' in (sys.argv if argv is None else argv) else [])
    params = read_parameters()
    in_use = set()
    natives, globals_block, functions = [], [], []
    map_decl = engine_ref = None
    for p in listing:
        texts = []
        for n in part_names(p):
            file_path = part_path(n)
            if not os.path.isfile(file_path):
                print('WARNING: missing %s (empty part)' % file_path)
                continue
            body_text = apply_includes(read_latin1(file_path), file_path, read_latin1)
            body_text = apply_conditionals(body_text, file_path, params, in_use)
            body_text = apply_parameters(body_text, file_path, params, in_use)
            if n.startswith('KKN:'):
                if map_decl is None:
                    map_decl = map_native_declarations(arg('source', war3map_source(), argv))[0]
                    map_decl = dict((k, v) for k, v in map_decl.items() if k not in NO_STUB)
                    engine_ref = set(RX_ANY_DEF.findall(read_latin1(os.path.join(REF, 'common.j'))))
                    engine_ref |= set(RX_ANY_DEF.findall(read_latin1(os.path.join(REF, 'blizzard.j'))))
                    engine_ref |= _defined_in_fixed_parts(listing, params)
                body_text = filter_conditional_natives(body_text, file_path, map_decl, engine_ref)
                engine_ref |= implemented_names(body_text)
            texts.append(body_text)
        if not texts or (not any(texts) and any(n.startswith('KKN:') for n in part_names(p))):
            continue
        t = ''.join(texts)
        while '//@SLOTGLOBALS' in t and '//@ENDSLOTGLOBALS' in t:
            i = t.index('//@SLOTGLOBALS')
            j = t.index('//@ENDSLOTGLOBALS')
            globals_block += [line.strip() for line in t[i + len('//@SLOTGLOBALS'):j].split('\n') if line.strip()]
            t = t[:i] + t[j + len('//@ENDSLOTGLOBALS'):]
        while '//@GLOBALS' in t and '//@ENDGLOBALS' in t:
            i = t.index('//@GLOBALS')
            j = t.index('//@ENDGLOBALS')
            globals_block += [line.strip() for line in t[i + 10:j].split('\n') if line.strip()]
            t = t[:i] + t[j + 13:]
        body = []
        for line in t.split('\n'):
            s = line.strip()
            if s.startswith('native ') or s.startswith('constant native '):
                natives.append(s)
                continue
            no_comment = line.split('//')[0].rstrip() if '//' in line else line
            if RX_GLOBAL.match(no_comment):
                globals_block.append(no_comment.strip() if no_comment.strip() else s)
            else:
                body.append(line)
        functions.append('// ===== %s =====' % display_name(p))
        functions += body
    leftover = sorted(set(params) - in_use)
    if leftover:
        raise SystemExit('ABORT: %s has a value that no part asks for: %s' % (PARAMETROS, ', '.join(leftover)))
    return natives, globals_block, functions


def natives_of_map():
    _demand_check()
    if not os.path.isfile(MAP_NATIVES):
        return set()
    t = open(MAP_NATIVES, 'rb').read().decode('latin-1')
    return set(re.findall(r'(?m)^\s*native\s+([A-Za-z_]\w*)\s+takes\s', t))


def main(argv=None):
    _demand_check()
    argv = sys.argv[1:] if argv is None else list(argv)
    output = arg('output', DEFAULT_OUTPUT, argv)
    origin = arg('source', war3map_source(), argv)
    print('source of the natives: %s' % origin)
    decl, order = map_native_declarations(origin)
    order = [n for n in order if n not in NO_STUB]
    map_path = open(origin, 'rb').read().decode('utf-8', 'surrogateescape')
    map_path = re.sub(r'\r(?!\n)', '\n', map_path)
    print('natives declared in the map: %d' % len(order))
    if not os.path.isdir(ANALYSIS):
        os.makedirs(ANALYSIS)
    with open(os.path.join(ANALYSIS, 'assinaturas_nativas.json'), 'w', encoding='utf-8') as fh:
        json.dump({'order': order, 'decl': decl}, fh, ensure_ascii=False, indent=1)

    in_layer = natives_of_map()
    if in_layer:
        print('declared by the MAP (outside blizzard.j): %s' % ', '.join(sorted(in_layer)))

    natives, g, functions = read_parts(argv)
    functions_block = '\n'.join(functions)
    if not functions_block.strip() and not g:
        print('nothing to generate: the parts of the layer are empty')
        return 2

    layer = arg('layer', None, argv)
    smoke_mode = '--stubs' in argv

    engine = set(RX_ANY_DEF.findall(read_latin1(os.path.join(REF, 'common.j'))))
    engine |= set(RX_ANY_DEF.findall(read_latin1(os.path.join(REF, 'blizzard.j'))))

    if smoke_mode:
        j_delivery = os.path.join(ROOT, 'scripts', 'war3map.j')
        map_txt = (open(j_delivery, 'rb').read().decode('utf-8', 'surrogateescape')
                   if os.path.isfile(j_delivery) else map_path)
        functions_block, list_a, list_b = smoke_stubs(
            decl, order, in_layer, functions_block, map_txt, engine)
        print('SMOKE: %d stubs (A: natives of the map) + %d stubs (B: functions the map calls)'
              % (len(list_a), len(list_b)))
    else:
        map_own = set(re.findall(r'(?m)^[ \t]*(?:constant[ \t]+)?function[ \t]+([A-Za-z_]\w*)[ \t]+takes', map_path))
        clashes = sorted(implemented_names(functions_block) & map_own)
        if clashes:
            print(
                'WARNING: %d function(s) of the layer with the name of a function of the map: the one of the map wins, the one of the layer becomes'
                'kkc_<name>: %s' % (len(clashes), ', '.join(clashes[:12]))
            )
            functions_block = re.sub(r'\b(%s)\b' % '|'.join(map(re.escape, clashes)), r'kkc_\1', functions_block)
        m_globals = re.search(r'(?ms)^[ \t]*globals[ \t]*$(.*?)^[ \t]*endglobals\b', map_path.replace('\r', ''))
        rx_decl = re.compile(r'^[ \t]*(?:constant[ \t]+)?[A-Za-z_]\w*[ \t]+(?:array[ \t]+)?([A-Za-z_]\w*)')
        map_globals = set(
            m.group(1)
            for m in (rx_decl.match(line) for line in (m_globals.group(1).split('\n') if m_globals else []))
            if m and m.group(1) not in ('function', 'native', 'type')
        )
        layer_global_names = set(m.group(1) for m in (rx_decl.match(line.split('//')[0]) for line in g) if m)
        global_clash_list = sorted(map_globals & layer_global_names)
        if global_clash_list:
            print(
                'WARNING: %d layer global(s) with the name of a map global: the map one is kept, the layer one becomes '
                'kkc_<name>: %s' % (len(global_clash_list), ', '.join(global_clash_list[:12]))
            )
            rx_global_clash = re.compile(r'\b(%s)\b' % '|'.join(map(re.escape, global_clash_list)))
            g = [rx_global_clash.sub(r'kkc_\1', line) for line in g]
            functions_block = rx_global_clash.sub(r'kkc_\1', functions_block)
        done_names = implemented_names(functions_block)
        stubs = make_stubs(decl, order, done_names | in_layer)
        functions_block = functions_block + '\n\n' + stubs

        existing = set(re.findall(r'(?m)^(?:native|function)\s+([A-Za-z_]\w*)\s+takes\s',
                                  read_latin1(os.path.join(REF, 'common.j'))))
        existing |= set(re.findall(r'(?m)^function\s+([A-Za-z_]\w*)\s+takes\s',
                                   read_latin1(os.path.join(REF, 'blizzard.j'))))
        functions_block, n_sorted = sort_by_dependency(functions_block, existing)
        print('functions sorted by dependency: %d' % n_sorted)
        print('natives with hand-written body: %d of %d' % (len(done_names & set(order)), len(order)))
        print('engine natives declared by us: %d | variables in globals: %d'
              % (len(natives), len(g)))

    before = '\n'.join(natives)
    after_diag = functions_block
    g = '\n'.join(line for line in g if line.strip())

    if layer:
        score = ('SMOKE MODE (--stubs): NEUTRAL bodies in the platform natives, only to measure\n'
                 '// SIZE against MECHANISM. NOT for playing.'
                 if smoke_mode else
                 'REAL MODE: the logic of the platform natives, from port/compat/*.j.')
        raw_bytes = write_layer(layer, before, g, after_diag, score)
        nf = len(RX_FUNC_DEF.findall(after_diag))
        print('layer written: %s (%d B, %d natives, %d lines of globals, %d functions)'
              % (layer, len(raw_bytes), len(natives), len(g.split('\n')), nf))
        return 0

    line_list = read_latin1(os.path.join(REF, 'blizzard.j')).split('\n')
    eg = [i for i, line in enumerate(line_list) if re.match(r'^\s*endglobals\b', line)]
    if len(eg) != 1:
        print('FAIL: expected 1 endglobals in the reference blizzard.j, found %d' % len(eg))
        return 2
    eg = eg[0]
    header = BLIZZARD_HEADER or default_header()
    output_lines = (before.split('\n') + header + line_list[:eg] + [''] + g.split('\n') + line_list[eg:] +
                    ['', ''] + after_diag.split('\n'))
    if not os.path.isdir(os.path.dirname(os.path.abspath(output))):
        os.makedirs(os.path.dirname(os.path.abspath(output)))
    open(output, 'wb').write(('\n'.join(output_lines) + '\n').encode('latin-1', 'replace'))
    print('written: %s (%d lines, %d B)'
          % (output, len(output_lines), os.path.getsize(output)))

    if '--sem-pjass' in argv:
        return 0
    cmd = GATE or [sys.executable, PJASS_PY, '--root=' + ROOT, '--ref=' + REF, '--conjunto',
                   '--blizzard=' + os.path.abspath(output)]
    r = subprocess.run(cmd, capture_output=True, text=True, errors='replace')
    print(r.stdout[-9000:])
    if r.stderr.strip():
        print(r.stderr[-2000:])
    return r.returncode


def _cli(argv):
    root = arg('root', None, argv)
    listing = arg('pieces', None, argv)
    if not root or not listing:
        print(__doc__)
        print('MISSING --raiz=<project> and --partes=<list.json>')
        return 2
    datum = json.load(open(listing, encoding='utf-8'))
    if isinstance(datum, dict):
        pieces, wave1 = datum.get('pieces', []), datum.get('wave1_parts', [])
    else:
        pieces, wave1 = datum, []
    configure_layer(root, [tuple(p) if isinstance(p, list) else p for p in pieces],
                    [tuple(p) if isinstance(p, list) else p for p in wave1])
    return main([a for a in argv if not a.startswith('--root=') and not a.startswith('--pieces=')])


if __name__ == '__main__':
    sys.exit(_cli(sys.argv[1:]))
